config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'

  resources :prototypes do
    resources :comments, only: [:create, :update, :destroy]
    resources :likes, only: [:create, :destroy]
end
  resources :users, only: [:show, :edit, :update]
end

app/models/_create_articles.rb
class CreateArticles < ActiveRecord::Migration[5.0]
  def change
    create_table :articles do |t|
      t.string :title
      t.text :body
      t.references :user, foreign_key: true

      t.timestamps
    end
    add_index :articles,[:user_id,:created_at]
  end
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :prototype

  mount_uploader :content, PrototypeImageUploader

  enum status: %i(main sub)

  validates :content,
            :status,
            presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype

  validates :content, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count
end

app/models/pro_tag.rb
class ProTag < ActiveRecord::Base
  belongs_to :prototype
  belongs_to :tag_name
  validates :prototype_id, presence: true
  validates :tag_name_id presence: true
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  belongs_to :user
  has_many :captured_images, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :tag_names, through: :pro_tag
  has_many :pro_tags, dependent: :destroy

  accepts_nested_attributes_for :captured_images, reject_if: :reject_sub_images, allow_destroy: true

  validates :title,
            :catch_copy,
            :concept,
            presence: true

  def reject_sub_images(attributed)
    attributed['content'].blank?
  end

  def set_main_thumbnail
    captured_images.main.first.content
  end

  def posted_date
    created_at.strftime('%b %d %a')
  end

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def save_tag_names(tags)
    current_tags = self.tag_names.plunk(:name) unless self.tag_names.nill?
    old_tags = current_tags - tags
    new_tags = tags - current_tags
    #Destroy old taggings:
    old_tags.each do |old_name|
     self.tag_names.delete Tag_names.find_by(name:old_name)
   end
   #Create new taggings:
    new_tags.each do |new_name|
    prototype_tag_name = Tag_name.find_or_create_by(name:new_name)
    self.tag_names << prototype_tag_name
    end
  end
end

app/models/tag_map.rb
class CreateProTags < ActiveRecord::Migration
  def change
    create_table :tag_maps do |t|
      t.references :tags_name, foreign_key: true
      t.references :prototype, foreign_key: true
      t.timestamps null: false
    end
  end
end

app/models/tags_name.rb
class TagsName < ActiveRecord::Base
  t.string :content
end

has_many :prototypes,through: :tag_map

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, UserImageUploader

  has_many :prototypes
  has_many :comments
  has_many :likes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :profile, :position, :occupation, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys:[:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    @comment = Comment.create(content: comment_params[:content], prototype_id: comment_params[:prototype_id], user_id: current_user.id)
    prototype = Prototype.find(params[:prototype_id])
    @comments = prototype.comments.includes(:user)
    redirect_to "/prototypes/#{@comment.prototype.id}"
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
  def comment_params
    # params.permit(:content, :prototype_id, :user_id)
    params.require(:comment).permit(:content).merge(prototype_id: params[:prototype_id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @prototype = Prototype.find(params[:prototype_id])
    like = current_user.likes.build(prototype_id: @prototype.id)
    like.save
    @prototype.reload
    # # @prototype = Prototype.find(params[:prototype_id])
    # like = Like.create(user_id: current_user.id, prototype_id: params[:prototype_id])
    # # @likes = Like.where(prototype_id: params[:prototype_id])
    # redirect_to (:back), notice: 'いいね！しました'
    # # redirect_to prototype_path(@like.prototype.id), notice: 'いいね！しました'

  end

  def destroy
    @prototype = Prototype.find(params[:prototype_id])
    like = current_user.likes.find_by(prototype_id: @prototype.id)
    like.destroy
    @prototype.reload
    # # @prototype = Prototype.find(params[:prototype_id])
    # like = Like.find_by(user_id: current_user.id, prototype_id: params[:prototype_id])
    # like.destroy
    # # @likes = Like.where(prototype_id: params[:prototype_id])
    # redirect_to (:back), notice: 'いいね！取消しました'
    # # redirect_to prototype_path(prototype.prototype.id), notice: 'いいね！取消しました'
    # # render 'prototypes/show'
  end

end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: :show

  def index
    @prototypes = Prototype.page(params[:page]).per(8).order('updated_at DESC')
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      redirect_to :root, notice: '登録出来ました'
    else
      redirect_to ({ action: 'new' }), alert: '登録できません'
     end
  end

  def show
    @prototype = Prototype.find(params[:id])
    @comments = @prototype.comments.includes(:user)
    @new_comment = @prototype.comments.build
  end

  def destroy
      prototype = Prototype.find(params[:id])
      prototype.destroy if prototype.user_id == current_user.id
  end

  def edit
    @prototype = Prototype.find(params[:id])
  end

  def update
      prototype = Prototype.find(params[:id])
      prototype.update(update_prototype_params) if prototype.user_id == current_user.id
      redirect_to prototype_path, notice: '編集しました'
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:content, :status]
    )
  end

  def update_prototype_params
    params.require(:prototype).permit(
      :title,
      :catch_copy,
      :concept,
      :user_id,
      captured_images_attributes: [:content, :status, :id]
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @prototypes = @user.prototypes
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to :root, notice: 'Your user infomation was successfully updated'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :position,
      :profile,
      :occupation,
      :avatar
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" =>  "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>  true
    = javascript_include_tag 'application', 'data-turbolinks-track' =>  true
    = csrf_meta_tags
  %body
    = render "shared/header"
    = render "shared/messages"
    = yield
    = render "shared/footer"

app/views/likes/_like_links.html.haml
- if user_signed_in?
  - if @prototype.like_user(current_user.id)
    = button_to prototype_like_path(@prototype, id:params), method: :delete, id: "like-button", remote: true do
      .likeicon-red
        = fa_icon 'heart 2x'
      %span like
      %span
        = @prototype.likes_count
  - else
    = button_to prototype_likes_path(@prototype), id: "like-button", remote: true do
      .likeicon
        = fa_icon 'gratipay 2x'
      %span like
      %span
        = @prototype.likes_count
- else
  .likeicon
    = fa_icon 'gratipay 2x'
  %span
    = @prototype.likes_count

app/views/likes/create.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links", prototype: @prototype)) %>');
$('#like-count').html('<%= @prototype.likes_count %>');

app/views/likes/destroy.js.erb
$('#like-link').html('<%= escape_javascript(render("likes/like_links", prototype: @prototype)) %>');
$('#like-count').html('<%= @prototype.likes_count %>');

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && current_user.id == prototype.user_id
    .dropdown-drop_menu_location-open
      %button#dropdownMenu.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "data-toggle" => "dropdown", :type => "button"}Action
      %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
        %li
          %a{"data-method" => "delete", :href => "/prototypes/#{prototype.id}", :rel => "nofollow"} Delete
        %li
          %a{:href => "/prototypes/#{prototype.id}/edit"} Edit
  .thumbnail
    = link_to image_tag(prototype.set_main_thumbnail), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-user
          = link_to prototype.user.name, user_path(prototype.user)
        .proto-posted
          = prototype.posted_date

app/views/prototypes/destroy.html.haml
%p
  削除が完了しました。
%a{:href => "/"} 投稿一覧へ戻る

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images, @prototype.captured_images.main.first do |image|
              / %img
              = image.file_field :content, required: true, :class => 'pic'
              = image.hidden_field :status, value: "main"
            .preview
              - if @prototype.captured_images.main.first.present?
                = image_tag(@prototype.captured_images.main.first.content, alt:"test", class:"resizeimage")
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images,@prototype.captured_images.sub[i] do |image|
                    / %img
                    = image.file_field :content, :class => 'pic'
                    = image.hidden_field :status, value: "sub"
                    .preview
                      = image_tag(image.object.content, alt:"test", class:"resizeimage")
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.btn-default.btn-popular
          = link_to "Popular", "#"
        %li.btn-default.btn-popular
          = link_to "Newest", "#"
      = link_to "VIEW TAGS", "#", class: "btn btn-default col-lg-1"

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

    = paginate @prototypes

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = f.hidden_field :user_id, value: current_user.id
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h4 Title
          .proto-new-title
            = f.text_field :title, required: true, autofocus: true, placeholder: "Input Title"
      .row
        .col-md-12
          %h4 Main Thumbnail
          .cover-image-upload#main_image_uploader
            = f.fields_for :captured_images do |image|
              / %img
              = image.file_field :content, required: true, :class => 'pic'
              = image.hidden_field :status, value: "main"
            .preview
        .col-md-12
          %h4 Sub Thumbnails
          %ul.proto-sub-list.list-group
            - 3.times do |i|
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :captured_images do |image|
                    / %img
                    = image.file_field :content, :class => 'pic'
                    = image.hidden_field :status, value: "sub"
                    .preview
      .row.proto-description
        .col-md-12
          %h4 Catch Copy
          = f.text_field :catch_copy, require: true, placeholder: "Input Catch Copy"
        .col-md-12
          %h4 Concept
          = f.text_area :concept, require: true, placeholder: "Input Concept"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
    .col-md-6.clearfix
      .likes_box
        #like-link
          = render "likes/like_links", prototype: @prototype

  .row
    .col-md-9.image-box
      = image_tag(@prototype.set_main_thumbnail.large, class: 'img-responsive img-size-fix', style: "margin: 0 auto;")
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.captured_images.sub.each do |image|
          %li.list-group-item
            = image_tag(image.content, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li
          %a{href: "#", class: "btn btn-default"} iPad
        %li
          %a{href: "#", class: "btn btn-default"} wireframe
  .row.proto-comment
    %h4.col-md-12 Comments(#{@prototype.comments.count})
    #comment_area.col-md-8
      .media
        .media-left
        .media-body
          - if @comments
            - @comments.each do |comment|
              = comment.user.name
              = comment.content
              %br

    .form-inline
      %h4 Write a comment
      .row
        .form-group.col-md-10
          =form_tag("/prototypes/#{@prototype.id}/comments", method: :post, id: "new_comment") do
            %textarea.textbox{:cols => "30", :name => "comment[content]", :placeholder => "コメントする", :rows => "2"}
            %input.form-group.col.md-2{:type => "submit", :value => "SENT"}/

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand
      = link_to image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px"), root_path
    .navbar-collapse.collapse.navbar-responsive-collapse
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: 'dropdown-toggle', role: 'button', 'aria-expanded' =>  'false', 'data-toggle' => 'dropdown' do
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Edit', edit_user_path(current_user)
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
          %li
            .btn.btn-default
              = link_to "New Photo", new_prototype_path, style: "color: #337ab7;"
      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_session_path

app/views/shared/_messages.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert--success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert--danger")

app/views/users/edit.html.haml
.container.user-new.clearfix
  = form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit
          .user-name_image.row
            .user-name.col-md-10
              = f.text_field :name, placeholder: "Input Username", autofocus: true, required: true
            .user-image.col-md-2
              %img{ style: "" }
              = f.file_field :avatar
          .user-email
            = f.text_field :email, placeholder: "Input Email", required: true
        .col-md-12
          %h4 Position
          .user-user-member.row
            .user-name.col-md-12
              = f.text_field :position, placeholder: "Input Position"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, placeholder: "Input Profile", size:"30×4"
          %h4 Occupation
          .user-name_image.row
            .user-name.col-md-12
              = f.text_area :occupation, placeholder: "Input Occupation", size: "30×4"
        .row.text-center.user-btn
          .actions
            = f.submit "SAVE", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        = image_tag(@user.avatar.thumb, alt: "profile_photo", class: "media-object", style: "width: 64px; height: 64px;")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree= @user.position
        .row
          .col-md-6
            %h4 Profile
            %p= @user.profile
          .col-md-6
            %h4 Occupation
            %p= @user.occupation
.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes